version: '3.5'
services: 
    mariadb:
        image: mariadb
        env_file: .env
        volumes: 
            - db:/var/lib/mysql
        restart: always
        build: requirements/mariadb/
        networks: 
            - qcesar_network
        container_name: mariadb
    nginx:
        image: nginx
        env_file: .env
        volumes: 
            - wp:/var/www/wordpress
        depends_on: 
            - wordpress
        ports: 
            - "443:443"
        restart: always
        build: requirements/nginx/
        networks: 
            - qcesar_network
        container_name: nginx

    wordpress:
        image: wordpress
        env_file: .env
        volumes: 
            - wp:/var/www/wordpress
        depends_on: 
            - mariadb
        restart: always
        build: requirements/wordpress
        networks: 
            - qcesar_network
        container_name: wordpress
volumes:
    wp:
        driver: local
        name: wp
        driver_opts: 
            type: none
            o: bind
            device: /home/qcesar/data/wp
    db:
        driver: local
        name: db
        driver_opts: 
            type: none
            o: bind
            device: /home/qcesar/data/db
networks: 
    qcesar_network:
        name: qcesar_network
        driver: bridge



